---
title: "st499"
author: "Grace Salo"
date: "1/28/2022"
output: html_document
---

## Setup
```{r setup}
# load packages
library(ggplot2)
library(dplyr)

# import data
data <- read.csv("simulated_data.csv")
    # NOTE: data set has 61 (odd # obs)
colnames(data) <- c('Time', 'Base', 'Noise1', 'Noise5', 'Noise10', 'ReturnBase', 'Return1', 'Return5', 'Return10')
head(data)
tail(data)
```

## EDA
```{r eda}
# Scatterplot: Base, Noise1, Noise5, Noise10 vs. Time
ggplot(data=data) + geom_point(aes(x=Time, y=Noise10), color="purple") + geom_point(aes(x=Time, y=Noise5), color="blue") + geom_point(aes(x=Time, y=Noise1), color="green") + geom_point(aes(x=Time, y=Base), color="yellow") + labs(title="Base, Noise1, Noise5, Noise10 vs. Time", caption="Base=yellow, Noise1=green, Noise5=blue, Noise10=purple")

# Scatterplot: ReturnBase, Return1, Return5, Return10 vs. Time
ggplot(data=data) + geom_point(aes(x=Time, y=Return10), color="purple") + geom_point(aes(x=Time, y=Return5), color="blue") + geom_point(aes(x=Time, y=Return1), color="green") + geom_point(aes(x=Time, y=ReturnBase), color="yellow") + labs(title="ReturnBase, Return1, Return5, Return10 vs. Time", caption="ReturnBase=yellow, Return1=green, Return5=blue, Return10=purple")

# Return5 vs. Time with ReturnBase line of best fit
ggplot(data=data) + geom_point(aes(x=Time, y=Return5)) + geom_line(aes(x=Time, y=ReturnBase), color="blue") + labs(title="Return5 vs. Time with ReturnBase line (blue)")


# print some!
png(file="Base-Noise_vs_Time.png", width=450, height=450)
ggplot(data=data) + geom_point(aes(x=Time, y=Noise10), color="purple") + geom_point(aes(x=Time, y=Noise5), color="blue") + geom_point(aes(x=Time, y=Noise1), color="green") + geom_point(aes(x=Time, y=Base), color="yellow") + labs(title="Base, Noise1, Noise5, Noise10 vs. Time", caption="Base=yellow, Noise1=green, Noise5=blue, Noise10=purple")
dev.off()
```


## Model: ReturnBase ~ Time and Prediction
#### returnbase final
```{r returnbase}
# set starting number of obs (n)
n <- 30

# subset data into (1:n) and (n+1, end)
train <- data %>% filter(Time <= n) %>% select(Time, ReturnBase)
test <- data %>% filter(Time > n) %>% select(Time, ReturnBase)

# model ReturnBase ~ Time
mod <- lm(ReturnBase ~ Time, data=train)
summary(mod)
# plot of predicted return values from model
ggplot(data=train) + geom_point(aes(x=Time, y=mod$coefficients[1] + 
  mod$coefficients[2]*Time)) + labs(x=paste0("1st n=",n), y="Predicted values of Return \n from Linear Model", title=paste0("n=",n," predicted return from model"), subtitle="model: ReturnBase ~ Time")

# predict 2nd part of values
pred <- predict(object=mod, newdata=test)

# add column to final dataset with predicted values
final <- data %>% select(Time, Base, ReturnBase) %>% 
  mutate(PredReturnBase = append(data[1:n, "ReturnBase"], pred))

# plot new data with predicted values of ReturnBase in the second half
ggplot(data=final) + geom_point(aes(x=Time, y=PredReturnBase)) + 
  labs(title=paste0("n=",n," original obs + n=",(nrow(data)-n)," predicted obs of Return"), subtitle="model: ReturnBase ~ Time")

# create PredBase from exp(PredReturnBase[i])*Base[i-1]
final <- final %>% mutate(PredBase = exp(PredReturnBase)*lag(Base))
# set first PredBase to original Base value
final$PredBase[1] = final$Base[1]

# plot PredBase vs. Time
ggplot(data=final) + 
  geom_point(aes(x=Time, y=PredBase), color="blue") +
  geom_point(aes(x=Time, y=Base), color="green") + 
  labs(title="Base vs. Time", subtitle="Original (green) and Predicted (blue) data")

# calculate residuals (should be 0 for base)
final <- final %>% mutate(res = PredReturnBase - ReturnBase)

# plot histogram of residuals
ggplot(data=final) + geom_histogram(aes(x=res), bins=nrow(final))

# calculate MAPE
a <- final %>% mutate(MAPE = abs((Base-PredBase)/Base)) %>% select(MAPE)
MAPEbase = (1/nrow(a))*sum(a)
# OR
(1/nrow(final))*sum(abs((final$Base-final$PredBase)/final$Base))


# plot PredReturnBase and ReturnBase vs. Time
ggplot(data=final) + 
  geom_line(aes(x=Time, y=append(rep(NA,n), pred)), color="blue") + 
  geom_point(aes(x=Time, y=ReturnBase), color="green") +
  labs(title=paste0("Green:  Original n=",nrow(final)," ReturnBase data \nBlue:     Predicted line from n=",(nrow(final)-n)," PredReturnBase data"), subtitle=paste0("model: ReturnBase ~ Time with n=",n), y="ReturnBase;  PredReturnBase")
```




## Model: Return1 ~ Time and Prediction
#### return1 final
```{r return1}
# set starting number of obs (n)
n = 20

# subset data into (1:n) and (n+1, end)
train <- data %>% filter(Time <= n) %>% select(Time, Return1)
test <- data %>% filter(Time > n) %>% select(Time, Return1)

# model Return1 ~ Time
mod <- lm(Return1 ~ Time, data=train)
summary(mod)
# plot of predicted return values from model
ggplot(data=train) + geom_point(aes(x=Time, y=mod$coefficients[1] + 
  mod$coefficients[2]*Time)) + labs(x=paste0("1st n=",n), y="Predicted values of Return \n from Linear Model", title=paste0("n=",n," predicted return from model"), subtitle="model: Return1 ~ Time")


# predict 2nd part of values
pred <- predict(object=mod, newdata=test)

# add column to final dataset with predicted values
final <- data %>% select(Time, Noise1, Return1) %>% 
  mutate(PredReturn1 = append(data[1:n, "Return1"], pred))

# plot new data with predicted values of ReturnBase in the second half
ggplot(data=final) + geom_point(aes(x=Time, y=PredReturn1)) + 
  labs(title=paste0("n=",n," original obs + n=",(nrow(data)-n)," predicted obs of Return"), subtitle="model: Return1 ~ Time")

# create Pred1 from exp(PredReturn1[i])*Noise1[i-1]
final <- final %>% mutate(Pred1 = exp(PredReturn1)*lag(Noise1))
# set first Pred1 to original Noise1 value
final$Pred1[1] = final$Noise1[1]

# plot Pred1 vs. Time (and print!)
#png(file="Noise1-Pred1_vs_Time.png", width=450, height=450)
ggplot(data=final) + 
  geom_point(aes(x=Time, y=Pred1), color="blue") +
  geom_point(aes(x=Time, y=Noise1), color="green") + 
  labs(title="Noise1 vs. Time", subtitle="Original (green) and Predicted (blue) data")
#dev.off()

# calculate residuals
final <- final %>% mutate(res = PredReturn1 - Return1)

# plot histogram of residuals
ggplot(data=final) + geom_histogram(aes(x=res), bins=nrow(final))

# calculate MAPE
a <- final %>% mutate(MAPE = abs((Noise1-Pred1)/Noise1)) %>% select(MAPE)
MAPE1 <- (1/nrow(a))*sum(a)
# OR 
(1/nrow(final))*sum(abs((final$Noise1-final$Pred1)/final$Noise1))


# plot PredReturn1 and Return1 vs. Time
ggplot(data=final) + 
  geom_line(aes(x=Time, y=append(rep(NA,n), pred)), color="blue") + 
  geom_point(aes(x=Time, y=Return1), color="green") +
  labs(title=paste0("Green:  Original n=",nrow(final)," Return1 data \nBlue:     Predicted line from n=",(nrow(final)-n)," PredReturn1 data"), subtitle=paste0("model: Return1 ~ Time with n=",n), y="Return1;  PredReturn1")
```


## Model: Return5 ~ Time and Prediction
#### return5 final
```{r return5}
# set starting number of obs (n)
n = 20

# subset data into (1:n) and (n+1, end)
train <- data %>% filter(Time <= n) %>% select(Time, Return5)
test <- data %>% filter(Time > n) %>% select(Time, Return5)

# model Return5 ~ Time
mod <- lm(Return5 ~ Time, data=train)
summary(mod)
# plot of predicted return values from model
ggplot(data=train) + geom_point(aes(x=Time, y=mod$coefficients[1] + 
  mod$coefficients[2]*Time)) + labs(x=paste0("1st n=",n), y="Predicted values of Return \n from Linear Model", title=paste0("n=",n," predicted return from model"), subtitle="model: Return5 ~ Time")


# predict 2nd part of values
pred <- predict(object=mod, newdata=test)

# add column to final dataset with predicted values
final <- data %>% select(Time, Noise5, Return5) %>% 
  mutate(PredReturn5 = append(data[1:n, "Return5"], pred))

# plot new data with predicted values of ReturnBase in the second half
ggplot(data=final) + geom_point(aes(x=Time, y=PredReturn5)) + 
  labs(title=paste0("n=",n," original obs + n=",(nrow(data)-n)," predicted obs of Return"), subtitle="model: Return5 ~ Time")

# create Pred5 from exp(PredReturn5[i])*Noise5[i-1]
final <- final %>% mutate(Pred5 = exp(PredReturn5)*lag(Noise5))
# set first Pred5 to original Noise5 value
final$Pred5[1] = final$Noise5[1]

# plot Pred5 vs. Time
ggplot(data=final) + 
  geom_point(aes(x=Time, y=Pred5), color="blue") +
  geom_point(aes(x=Time, y=Noise5), color="green") + 
  labs(title="Noise5 vs. Time", subtitle="Original (green) and Predicted (blue) data")

# calculate residuals
final <- final %>% mutate(res = PredReturn5 - Return5)

# plot histogram of residuals
ggplot(data=final) + geom_histogram(aes(x=res), bins=nrow(final))

# calculate MAPE
a <- final %>% mutate(MAPE = abs((Noise5-Pred5)/Noise5)) %>% select(MAPE)
MAPE5 <- (1/nrow(a))*sum(a)
# OR 
(1/nrow(final))*sum(abs((final$Noise5-final$Pred5)/final$Noise5))


# plot PredReturn5 and Return5 vs. Time
ggplot(data=final) + 
  geom_line(aes(x=Time, y=append(rep(NA,n), pred)), color="blue") + 
  geom_point(aes(x=Time, y=Return5), color="green") +
  labs(title=paste0("Green:  Original n=",nrow(final)," Return5 data \nBlue:     Predicted line from n=",(nrow(final)-n)," PredReturn5 data"), subtitle=paste0("model: Return5 ~ Time with n=",n), y="Return5; PredReturn5")
```




## Model: Return10 ~ Time and Prediction
#### return10 final
```{r return10}
# set starting number of obs (n)
n = 20

# subset data into (1:n) and (n+1, end)
train <- data %>% filter(Time <= n) %>% select(Time, Return10)
test <- data %>% filter(Time > n) %>% select(Time, Return10)

# model Return10 ~ Time
mod <- lm(Return10 ~ Time, data=train)
summary(mod)
# plot of predicted return values from model
ggplot(data=train) + geom_point(aes(x=Time, y=mod$coefficients[1] + 
  mod$coefficients[2]*Time)) + labs(x=paste0("1st n=",n), y="Predicted values of Return \n from Linear Model", title=paste0("n=",n," predicted return from model"), subtitle="model: Return10 ~ Time")


# predict 2nd part of values
pred <- predict(object=mod, newdata=test)

# add column to final dataset with predicted values
final <- data %>% select(Time, Noise10, Return10) %>% 
  mutate(PredReturn10 = append(data[1:n, "Return10"], pred))

# plot new data with predicted values of ReturnBase in the second half
ggplot(data=final) + geom_point(aes(x=Time, y=PredReturn10)) + 
  labs(title=paste0("n=",n," original obs + n=",(nrow(data)-n)," predicted obs of Return"), subtitle="model: Return10 ~ Time")

# create Pred10 from exp(PredReturn10[i])*Noise10[i-1]
final <- final %>% mutate(Pred10 = exp(PredReturn10)*lag(Noise10))
# set first Pred10 to original Noise10 value
final$Pred10[1] = final$Noise10[1]

# plot Pred10 vs. Time (and print!)
#png(file="Noise10-Pred10_vs_Time.png", width=450, height=450)
ggplot(data=final) + 
  geom_point(aes(x=Time, y=Pred10), color="blue") +
  geom_point(aes(x=Time, y=Noise10), color="green") + 
  labs(title="Noise10 vs. Time", subtitle="Original (green) and Predicted (blue) data")
#dev.off()

# calculate residuals
final <- final %>% mutate(res = PredReturn10 - Return10)

# plot histogram of residuals
ggplot(data=final) + geom_histogram(aes(x=res), bins=nrow(final))

# calculate MAPE
a <- final %>% mutate(MAPE = abs((Noise10-Pred10)/Noise10)) %>% select(MAPE)
MAPE10 <- (1/nrow(a))*sum(a)
# OR 
(1/nrow(final))*sum(abs((final$Noise10-final$Pred10)/final$Noise10))


# plot PredReturn10 and Return10 vs. Time
#png(file="PredReturn10_Return10_obs30.png", width=450, height=450)
ggplot(data=final) + 
  geom_line(aes(x=Time, y=append(rep(NA,n), pred)), color="blue") + 
  geom_point(aes(x=Time, y=Return10), color="green") +
  labs(title=paste0("Green:  Original n=",nrow(final)," Return10 data \nBlue:     Predicted line from n=",(nrow(final)-n)," PredReturn10 data"), subtitle=paste0("model: Return10 ~ Time with n=",n), y="Return10;  PredReturn10")
#dev.off()
```



```{r test}
# plan: create MAPE matrix from original 4 datasets (aka simulated_data.csv)
nobs = c(30, 25, 20, 15, 10, 5)
MAPEbase.all = data.frame('nobs'=nobs)

count = 0
MAPEbase = vector()
for(i in nobs) {
  count = count + 1
  # set starting number of obs (n)
  n = i
  
  # subset data into (1:n) and (n+1, end)
  train <- data %>% filter(Time <= n) %>% select(Time, ReturnBase)
  test <- data %>% filter(Time > n) %>% select(Time, ReturnBase)
  
  # model ReturnBase ~ Time
  mod <- lm(ReturnBase ~ Time, data=train)
  
  # predict 2nd part of values
  pred <- predict(object=mod, newdata=test)
  
  # add column to final dataset with predicted values
  final <- data %>% select(Time, Base, ReturnBase) %>% 
    mutate(PredReturnBase = append(data[1:n, "ReturnBase"], pred))
  
  # create PredBase from exp(PredReturnBase[i])*Base[i-1]
  final <- final %>% mutate(PredBase = exp(PredReturnBase)*lag(Base))
  # set first PredBase to original Base value
  final$PredBase[1] = final$Base[1]
  
  # calculate residuals (should be 0 for base)
  final <- final %>% mutate(res = PredReturnBase - ReturnBase)
  
  # calculate MAPE
  a <- final %>% mutate(MAPE = abs((Base-PredBase)/Base)) %>% select(MAPE)
  MAPE = (1/nrow(a))*sum(a)
  
  # add MAPE to vector
  MAPEbase = c(MAPEbase,MAPE)
}
MAPEbase
MAPEbase.all <- MAPEbase.all %>% mutate('MAPEbase' = MAPEbase)
MAPEbase.all


# create fn for PredBase
        # PROBLEM: can't pass column/dataframe names as arguments
reconstFn <- function(data, return, orig) {
  a <- list()
  for(i in 1:nrow(data)) {
    if(i==1) {
      b <- data %>% slice(i) %>% mutate(PredBase = {{orig}}) %>% select(PredBase)
      a <- append(a,b)
    }
    else {
      b <- data %>% slice(i) %>% mutate(PredBase = exp({{col}})*lag({{orig}})) %>% select(PredBase) 
      a <- append(a, b)
    }
  }
  data <- mutate(newCol = a)
  return(data)
}
a <- reconstFn(base.d20, PredReturnBase, Base)

reconstFn(base.d20, PredReturnBase, Base)
b <- base.d20  %>% select(PredReturnBase) %>% slice(3) %>% mutate(newCol = exp(PredReturnBase))
base.d20 <- base.d20 %>% mutate(PredBase = reconstFn(data, PredReturnBase))
```

```{r}

# set starting number of obs (n)
n <- 25

# subset data into (1:n) and (n+1, end)
train <- data %>% filter(Time <= n) %>% select(Time, ReturnBase)
test <- data %>% filter(Time > n) %>% select(Time, ReturnBase)

# model ReturnBase ~ Time
mod <- lm(ReturnBase ~ Time, data=train)
summary(mod)
# plot of predicted return values from model
ggplot(data=train) + geom_point(aes(x=Time, y=mod$coefficients[1] + 
  mod$coefficients[2]*Time)) + labs(x=paste0("1st n=",n), y="Predicted values of Return \n from Linear Model", title=paste0("n=",n," predicted return from model"), subtitle="model: ReturnBase ~ Time")

# predict 2nd part of values
pred <- predict(object=mod, newdata=test)

# add column to final dataset with predicted values
final <- data %>% select(Time, Base, ReturnBase) %>% 
  mutate(PredReturnBase = append(data[1:n, "ReturnBase"], pred))

# plot new data with predicted values of ReturnBase in the second half
ggplot(data=final) + geom_point(aes(x=Time, y=PredReturnBase)) + 
  labs(title=paste0("n=",n," original obs + n=",(nrow(data)-n)," predicted obs of Return"), subtitle="model: ReturnBase ~ Time")

# create PredBase from exp(PredReturnBase[i])*Base[i-1]
final <- final %>% mutate(PredBase = exp(PredReturnBase)*lag(Base))
# set first PredBase to original Base value
final$PredBase[1] = final$Base[1]

# plot PredBase vs. Time
ggplot(data=final) + 
  geom_point(aes(x=Time, y=PredBase), color="blue") +
  geom_point(aes(x=Time, y=Base), color="green") + 
  labs(title="Base vs. Time", subtitle="Original (green) and Predicted (blue) data")

# calculate residuals (should be 0 for base)
final <- final %>% mutate(res = PredReturnBase - ReturnBase)

# plot histogram of residuals
ggplot(data=final) + geom_histogram(aes(x=res), bins=nrow(final))

# calculate MAPE
a <- final %>% mutate(MAPE = abs((Base-PredBase)/Base)) %>% select(MAPE)
MAPEbase.25 = (1/nrow(a))*sum(a)
# OR
(1/nrow(final))*sum(abs((final$Base-final$PredBase)/final$Base))


# plot PredReturnBase and ReturnBase vs. Time
ggplot(data=final) + 
  geom_line(aes(x=Time, y=append(rep(NA,n), pred)), color="blue") + 
  geom_point(aes(x=Time, y=ReturnBase), color="green") +
  labs(title=paste0("Green:  Original n=",nrow(final)," ReturnBase data \nBlue:     Predicted line from n=",(nrow(final)-n)," PredReturnBase data"), subtitle=paste0("model: ReturnBase ~ Time with n=",n), y="ReturnBase;  PredReturnBase")



# set starting number of obs (n)
n <- 20

# subset data into (1:n) and (n+1, end)
train <- data %>% filter(Time <= n) %>% select(Time, ReturnBase)
test <- data %>% filter(Time > n) %>% select(Time, ReturnBase)

# model ReturnBase ~ Time
mod <- lm(ReturnBase ~ Time, data=train)
summary(mod)
# plot of predicted return values from model
ggplot(data=train) + geom_point(aes(x=Time, y=mod$coefficients[1] + 
  mod$coefficients[2]*Time)) + labs(x=paste0("1st n=",n), y="Predicted values of Return \n from Linear Model", title=paste0("n=",n," predicted return from model"), subtitle="model: ReturnBase ~ Time")

# predict 2nd part of values
pred <- predict(object=mod, newdata=test)

# add column to final dataset with predicted values
final <- data %>% select(Time, Base, ReturnBase) %>% 
  mutate(PredReturnBase = append(data[1:n, "ReturnBase"], pred))

# plot new data with predicted values of ReturnBase in the second half
ggplot(data=final) + geom_point(aes(x=Time, y=PredReturnBase)) + 
  labs(title=paste0("n=",n," original obs + n=",(nrow(data)-n)," predicted obs of Return"), subtitle="model: ReturnBase ~ Time")

# create PredBase from exp(PredReturnBase[i])*Base[i-1]
final <- final %>% mutate(PredBase = exp(PredReturnBase)*lag(Base))
# set first PredBase to original Base value
final$PredBase[1] = final$Base[1]

# plot PredBase vs. Time
ggplot(data=final) + 
  geom_point(aes(x=Time, y=PredBase), color="blue") +
  geom_point(aes(x=Time, y=Base), color="green") + 
  labs(title="Base vs. Time", subtitle="Original (green) and Predicted (blue) data")

# calculate residuals (should be 0 for base)
final <- final %>% mutate(res = PredReturnBase - ReturnBase)

# plot histogram of residuals
ggplot(data=final) + geom_histogram(aes(x=res), bins=nrow(final))

# calculate MAPE
a <- final %>% mutate(MAPE = abs((Base-PredBase)/Base)) %>% select(MAPE)
MAPEbase.20 = (1/nrow(a))*sum(a)
# OR
(1/nrow(final))*sum(abs((final$Base-final$PredBase)/final$Base))



# set starting number of obs (n)
n <- 15

# subset data into (1:n) and (n+1, end)
train <- data %>% filter(Time <= n) %>% select(Time, ReturnBase)
test <- data %>% filter(Time > n) %>% select(Time, ReturnBase)

# model ReturnBase ~ Time
mod <- lm(ReturnBase ~ Time, data=train)
summary(mod)
# plot of predicted return values from model
ggplot(data=train) + geom_point(aes(x=Time, y=mod$coefficients[1] + 
  mod$coefficients[2]*Time)) + labs(x=paste0("1st n=",n), y="Predicted values of Return \n from Linear Model", title=paste0("n=",n," predicted return from model"), subtitle="model: ReturnBase ~ Time")

# predict 2nd part of values
pred <- predict(object=mod, newdata=test)

# add column to final dataset with predicted values
final <- data %>% select(Time, Base, ReturnBase) %>% 
  mutate(PredReturnBase = append(data[1:n, "ReturnBase"], pred))

# plot new data with predicted values of ReturnBase in the second half
ggplot(data=final) + geom_point(aes(x=Time, y=PredReturnBase)) + 
  labs(title=paste0("n=",n," original obs + n=",(nrow(data)-n)," predicted obs of Return"), subtitle="model: ReturnBase ~ Time")

# create PredBase from exp(PredReturnBase[i])*Base[i-1]
final <- final %>% mutate(PredBase = exp(PredReturnBase)*lag(Base))
# set first PredBase to original Base value
final$PredBase[1] = final$Base[1]

# plot PredBase vs. Time
ggplot(data=final) + 
  geom_point(aes(x=Time, y=PredBase), color="blue") +
  geom_point(aes(x=Time, y=Base), color="green") + 
  labs(title="Base vs. Time", subtitle="Original (green) and Predicted (blue) data")

# calculate residuals (should be 0 for base)
final <- final %>% mutate(res = PredReturnBase - ReturnBase)

# plot histogram of residuals
ggplot(data=final) + geom_histogram(aes(x=res), bins=nrow(final))

# calculate MAPE
a <- final %>% mutate(MAPE = abs((Base-PredBase)/Base)) %>% select(MAPE)
MAPEbase.15 = (1/nrow(a))*sum(a)
# OR
(1/nrow(final))*sum(abs((final$Base-final$PredBase)/final$Base))



# set starting number of obs (n)
n <- 10

# subset data into (1:n) and (n+1, end)
train <- data %>% filter(Time <= n) %>% select(Time, ReturnBase)
test <- data %>% filter(Time > n) %>% select(Time, ReturnBase)

# model ReturnBase ~ Time
mod <- lm(ReturnBase ~ Time, data=train)
summary(mod)
# plot of predicted return values from model
ggplot(data=train) + geom_point(aes(x=Time, y=mod$coefficients[1] + 
  mod$coefficients[2]*Time)) + labs(x=paste0("1st n=",n), y="Predicted values of Return \n from Linear Model", title=paste0("n=",n," predicted return from model"), subtitle="model: ReturnBase ~ Time")

# predict 2nd part of values
pred <- predict(object=mod, newdata=test)

# add column to final dataset with predicted values
final <- data %>% select(Time, Base, ReturnBase) %>% 
  mutate(PredReturnBase = append(data[1:n, "ReturnBase"], pred))

# plot new data with predicted values of ReturnBase in the second half
ggplot(data=final) + geom_point(aes(x=Time, y=PredReturnBase)) + 
  labs(title=paste0("n=",n," original obs + n=",(nrow(data)-n)," predicted obs of Return"), subtitle="model: ReturnBase ~ Time")

# create PredBase from exp(PredReturnBase[i])*Base[i-1]
final <- final %>% mutate(PredBase = exp(PredReturnBase)*lag(Base))
# set first PredBase to original Base value
final$PredBase[1] = final$Base[1]

# plot PredBase vs. Time
ggplot(data=final) + 
  geom_point(aes(x=Time, y=PredBase), color="blue") +
  geom_point(aes(x=Time, y=Base), color="green") + 
  labs(title="Base vs. Time", subtitle="Original (green) and Predicted (blue) data")

# calculate residuals (should be 0 for base)
final <- final %>% mutate(res = PredReturnBase - ReturnBase)

# plot histogram of residuals
ggplot(data=final) + geom_histogram(aes(x=res), bins=nrow(final))

# calculate MAPE
a <- final %>% mutate(MAPE = abs((Base-PredBase)/Base)) %>% select(MAPE)
MAPEbase.10 = (1/nrow(a))*sum(a)
# OR
(1/nrow(final))*sum(abs((final$Base-final$PredBase)/final$Base))



# set starting number of obs (n)
n <- 5

# subset data into (1:n) and (n+1, end)
train <- data %>% filter(Time <= n) %>% select(Time, ReturnBase)
test <- data %>% filter(Time > n) %>% select(Time, ReturnBase)

# model ReturnBase ~ Time
mod <- lm(ReturnBase ~ Time, data=train)
summary(mod)
# plot of predicted return values from model
ggplot(data=train) + geom_point(aes(x=Time, y=mod$coefficients[1] + 
  mod$coefficients[2]*Time)) + labs(x=paste0("1st n=",n), y="Predicted values of Return \n from Linear Model", title=paste0("n=",n," predicted return from model"), subtitle="model: ReturnBase ~ Time")

# predict 2nd part of values
pred <- predict(object=mod, newdata=test)

# add column to final dataset with predicted values
final <- data %>% select(Time, Base, ReturnBase) %>% 
  mutate(PredReturnBase = append(data[1:n, "ReturnBase"], pred))

# plot new data with predicted values of ReturnBase in the second half
ggplot(data=final) + geom_point(aes(x=Time, y=PredReturnBase)) + 
  labs(title=paste0("n=",n," original obs + n=",(nrow(data)-n)," predicted obs of Return"), subtitle="model: ReturnBase ~ Time")

# create PredBase from exp(PredReturnBase[i])*Base[i-1]
final <- final %>% mutate(PredBase = exp(PredReturnBase)*lag(Base))
# set first PredBase to original Base value
final$PredBase[1] = final$Base[1]

# plot PredBase vs. Time
ggplot(data=final) + 
  geom_point(aes(x=Time, y=PredBase), color="blue") +
  geom_point(aes(x=Time, y=Base), color="green") + 
  labs(title="Base vs. Time", subtitle="Original (green) and Predicted (blue) data")

# calculate residuals (should be 0 for base)
final <- final %>% mutate(res = PredReturnBase - ReturnBase)

# plot histogram of residuals
ggplot(data=final) + geom_histogram(aes(x=res), bins=nrow(final))

# calculate MAPE
a <- final %>% mutate(MAPE = abs((Base-PredBase)/Base)) %>% select(MAPE)
MAPEbase.5 = (1/nrow(a))*sum(a)
# OR
(1/nrow(final))*sum(abs((final$Base-final$PredBase)/final$Base))



MAPEbase.all = append(MAPEbase.30, MAPEbase.25, MAPEbase.20, MAPEbase.15, MAPEbase.10, MAPEbase.5)
```




